# A reusable workflow that calls a local composite action.
name: 'A reusable workflow that calls a local composite action'

# NOTE: For slighly more involved example, see ./call-multi-file-actions.yml

on:
  workflow_call:
    inputs:
      who:
        description: 'Who to greet via action'
        required: false
        type: string
        default: 'World'

jobs:
  call-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run local action
        # NOTE:
        # - Referenced as if it's a remote (because it actually is remote from caller's perspective)
        #   instead of local relative like `uses: ./.github/actions/hello`
        #   - Because GitHub Actions doesn't support dynamic self-referencing
        #     that survives in caller's execution context.
        #     - Therefore hardcoded owner/repo is required.
        #       - WARN: Which mean this can break if the repository is renamed.
        uses: ryuheechul/playground-workflows/.github/actions/hello@main
        # INFO:
        # - The above comment about hardcoded owner/repo being required is not technically
        #   correct now that GitHub supports the new `$/` syntax (except for GHES).
        # - So, you can use the new `$/` syntax (e.g., `uses: $/.github/actions/hello`) for actions
        #   in the same repository without needing:
        #   - hardcoding (e.g., `uses: {owner}/{repo}/.github/actions/hello`)
        #   - or checking the repo with relative (e.g., `uses: ./.github/actions/hello`)
        # - See `./call-actions-with-dollar-syntax.yml` for an example.
        with:
          who: ${{ inputs.who }}
